version: '3.7'

services:
  postie:
    image: setherizor/postie
    env_file: .env
    ports:
      - '8000:8080'
    volumes:
      - postie-db:/usr/src/app/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postie-db:
